# Generated by Django 4.2 on 2023-04-18 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_tags_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
