# Generated by Django 4.2 on 2023-04-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_pix',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
